# Generated by Django 3.1.3 on 2021-03-12 21:11

from django.db import migrations, models
import django.db.models.deletion


def set_field(apps, schema_editor):
    migrations.RunSQL(
        """update store.cell set field_id = t.field_id
        from (
          SELECT f.id as field_id, c.id as cell_id
          FROM store_field f
          join store_record r on f.schema_id = r.schema_id 
          join store_cell c on c.field_name = f.name and c.record_id = r.id
        ) t
        where store_cell.id = t.cell_id"""
    )



class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.field'),
        ),
        migrations.RunPython(set_field,
                             reverse_code=migrations.RunPython.noop),
    ]
