# Generated by Django 3.1.3 on 2021-03-12 21:11

from django.db import migrations, models
import django.db.models.deletion


def set_field(apps, schema_editor):
    # Complete this function
    raise NotImplementedError



class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.field'),
        ),
        migrations.RunPython(set_field,
                             reverse_code=migrations.RunPython.noop),
    ]
