# Please pin the versions with `==` instead of `^`

[tool]
[tool.poetry]
name = "migration-exercise"
description = "Data migration exercise"
authors = []
version = "0.0.1"

[tool.poetry.dependencies]
python = ">=3.7,<3.9"
django = "==3.2.24"

[tool.poetry.dev-dependencies]
flake8 = "==3.8.3"
